# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-{{ checksum "mix.lock" }}
            - build-

      # specify any bash command here prefixed with `run: `
      - run: epmd -daemon
      - run: mix local.hex --force && mix local.rebar --force
      - run: mix deps.get
      - run: mix test

      - save_cache:
          key: build-{{ checksum "mix.lock" }}
          paths:
            - deps
            - _build
